language: android 
jdk: 
  - oraclejdk8 
android: 
  licenses:
    - '.+'
  components: 
    - tools 
    - build-tools-29.0.0 
    - android-29
    - Extra-android-support 
    - extra-google-google_play_services 
    - extra-android-m2repository 
    - extra-google-m2repository 
    - addon-google_apis-google-29    
before_deploy:
- export TRAVIS_TAG="release-$(git rev-parse --short ${TRAVIS_COMMIT})"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "Helas"
- git config --local user.email "helas@runbox.me"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
before_install: 
- yes | sdkmanager "build-tools;29.0.3"
- chmod +x gradlew 
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle 
- export JAVA_HOME=$JAVA8_HOME 
after_success: 
- chmod +x ./upload-gh-pages.sh
script: 
- ./gradlew build
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  api_key: $GITHUB_API_KEY
  file: 'app/build/outputs/apk/app-debug.apk'
  draft: true
  skip_cleanup: true
  on:
    branch: master
